spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kashi_kari
    username: test
    password: hoge00
    driverClassName: com.mysql.jdbc.Driver
    thymeleaf:
        cache: false
        mode: HTML
mybatis.configuration.mapUnderscoreToCamelCase: true
server:
    port: ${PORT:5000}
