spring:
  datasource:
    url: jdbc:mysql://us-cdbr-iron-east-01.cleardb.net/heroku_95649eb62666896
    username: bbb4551a46e7f6
    password: 0fd412b9
    driverClassName: com.mysql.jdbc.Driver
    thymeleaf:
        cache: false
        mode: HTML
mybatis.configuration.mapUnderscoreToCamelCase: true
server:
    port: ${PORT:5000}
